version: "3.8"

services:
  frontend:
    image: rnyn666140/primetrade-frontend:latest
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    image: rnyn666140/primetrade-backend:latest
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/intern_assignment
      - JWT_SECRET=supersecretkey
      - JWT_EXPIRES_IN=15m
      - CORS_ORIGIN=http://localhost:5173
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
      - ADMIN_SECRET_KEY=LMAO
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
